Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> #initialise the input for “length” and “diameter”
... 
... length = 90 
... 
... diameter = 6
... 
... #if the length or diameter is greater than 90cm
... #set the status to “reject”
... 
... if (length >= 90 or diameter >= 90): 
... 
...     valid = False
... 
... #otherwise, if the length plus twice the diameter is less than or equal to 104cm
... #set the status to “accept”
... 
... elif length + (2 * diameter) <= 104:
... 
...     valid = True 
... 
... #otherwise, if the length plus twice the diameter is more than 104cm
... #set the status to “reject”
... 
... elif length + (2 * diameter) > 104:
... 
...     valid = False
... 
... #if the status is “accept”
... #display that the tube does meet the criteria
... 
... if valid: 
... 
...     print('Does meet criteria') 
... 
... #otherwise
... #display that the tube does not meet the criteria
... 
... else: 
... 
